site:
  title: Antora GitHub Pages Demo
  start_page: antora-gh-pages-demo::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: css/vendor/tabs.css
      contents: './node_modules/@asciidoctor/tabs/dist/css/tabs.css'
    - path: js/vendor/tabs.js
      contents: './node_modules/@asciidoctor/tabs/dist/js/tabs.js'
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll

antora:
  extensions:
    - '@antora/lunr-extension'

asciidoc:
  extensions:
    - '@asciidoctor/tabs'
